language: c++

arch:
  - amd64
  - arm64 # please note arm64-graviton2 requires explicit virt: [lxd|vm] tag so it's recommended for jobs.include, see below
  # - ppc64le
  # - s390x

compiler:
  - gcc
  - clang

install: skip

script:
  - mkdir build && cd build
  # - conan install ..
  - cmake ..
  - cmake --build .

deploy:
  provider: releases
  api_key: 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
  file: build/bin/travisexample
  skip_cleanup: true
  # on:
  #   tags: true
