language: c++

arch:
  - amd64
  - arm64 # please note arm64-graviton2 requires explicit virt: [lxd|vm] tag so it's recommended for jobs.include, see below
  # - ppc64le
  # - s390x

compiler:
  - gcc
  - clang

install: skip

script:
  - mkdir build && cd build
  # - conan install ..
  - cmake ..
  - cmake --build .

deploy:
  provider: releases
  # user: sasha.antonchikov@gmail.com
  # password: ^t$gNeNfF_3!Rk#
  # api_key: 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
  api_key: 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
  file: build/bin/travisexample
  skip_cleanup: true
  # on:
  #   tags: true

notifications:
  webhooks:
    urls: https://discord.com/api/webhooks/847433788454731786/HZvM75P5FaRUeg893UUv53YJtmLWoe1Y5Kp45NDKU69dTr_F7LgL29qTNQ3JAF7gXXI4
    on_success: change
    on_failure: always
